# Generated by Django 3.0 on 2022-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подпись')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Историческая информация',
                'verbose_name_plural': 'блок информации',
            },
        ),
        migrations.DeleteModel(
            name='HistoryImageCaption',
        ),
        migrations.DeleteModel(
            name='HistoryImageNoCaption',
        ),
        migrations.DeleteModel(
            name='HistoryTextInfo',
        ),
    ]
