# Generated by Django 3.0 on 2022-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20220923_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='caption',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подпись'),
        ),
    ]
