# Generated by Django 3.0 on 2022-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение галереи')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
