# Generated by Django 3.0 on 2022-09-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['image'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'изображения'},
        ),
    ]
