# Generated by Django 3.0 on 2022-09-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='news/image/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, upload_to='news/video/', verbose_name='Видео')),
                ('utube', models.URLField(blank=True, verbose_name='Ссылка на видео на YouTube')),
            ],
        ),
    ]
