# Generated by Django 3.0 on 2022-09-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dates',
            options={'ordering': ['date'], 'verbose_name': 'Даты', 'verbose_name_plural': 'дата'},
        ),
    ]
