# Generated by Django 3.0 on 2022-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_auto_20220923_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.CharField(max_length=60, verbose_name='Дата события'),
        ),
    ]
