# Generated by Django 3.0 on 2022-09-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('address', models.CharField(max_length=40, verbose_name='Адрес')),
                ('mode', models.TextField(verbose_name='Режим работы')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Должность')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='staff/', verbose_name='Изображение')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.Department', verbose_name='Отдел')),
            ],
        ),
    ]
