# Generated by Django 3.0 on 2022-09-27 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Должность')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='staff/', verbose_name='Изображение')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.Department', verbose_name='Отдел')),
            ],
        ),
    ]
