# Generated by Django 3.0 on 2022-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
